---
version: '3'

services:
  mockserver:
    image: mockserver/mockserver:mockserver-snapshot
    environment:
     LOG_LEVEL: "OFF"
    ports:
    - 1080:1080

  performance:
    image: mockserver/mockserver:performance
    volumes:
    - "./performance_test.sh:/performance_test.sh"
    - "./locustfile.py:/locustfile.py"
    ports:
    - 8089:8089
    depends_on:
    - mockserver
    links:
    - "mockserver"
    environment:
      MOCKSERVER_HOST: "mockserver:1080"
    entrypoint:
    - "/performance_test.sh"

