---
version: '3'

services:
  mockserver:
    image: jamesdbloom/mockserver:latest
    environment:
      LOG_LEVEL: "WARN"

  performance:
    image: jamesdbloom/mockserver:performance
    volumes:
    - "./performance_test.sh:/performance_test.sh"
    depends_on:
    - mockserver
    links:
    - "mockserver"
    environment:
      MOCKSERVER_HOST: "mockserver:1080"
    command:
    - "/performance_test.sh"

