steps:
  - label: "update MockServer docker image"
    command: "docker pull jamesdbloom/mockserver:latest"

  - wait

  - label: "update wrk2 docker image"
    command: "docker pull jamesdbloom/mockserver:wrk2"

  - wait

  - label: "performance test"
    command: "docker-compose up"
