steps:
  - label: "update MockServer docker image"
    command: "docker pull jamesdbloom/mockserver:mockserver-snapshot"

  - wait

  - label: "update performance docker image"
    command: "docker pull jamesdbloom/mockserver:performance"

  - wait

  - label: "performance test"
    command: "docker-compose up --abort-on-container-exit"
